### ISSUE TITLE
The Wire.endTransmission after Wire.requestFrom is not needed.

### ISSUE THREAD

**Issue by Koepel** [orgua/iLib#4]
In the file "i2c.h" in the function "read" is a Wire.endTransmission at the end, after a Wire.requestFrom.
That last Wire.endTransmission can be deleted, since Wire.requestFrom should not be followed by a Wire.endTransmission.

The Wire.beginTransmission and Wire.endTransmission are only used when writing data.

**Comment by jlvandusen** [comment]
Koepel - thank you

**Comment by orgua** [comment]
ok, changed in latest dev-branch
